    # CUDA 8.0
    #
    # VERSION               0.0.1

    FROM      gcr.io/tensorflow/tensorflow:latest-gpu
    LABEL     maintainer="allen7575@gmail.com"

    ##
    ## Ubuntu - Packages - Search
    ## https://packages.ubuntu.com/search?suite=xenial&section=all&arch=amd64&searchon=contents&keywords=Search
    ##
    

    RUN apt update && apt -y install vim

